from pathlib import Path


FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _upload(client, project_id: int) -> None:
    with (FIXTURE_DIR / "preprocessing_sample.csv").open("rb") as handle:
        response = client.post(
            f"/projects/{project_id}/datasets/upload",
            data={"role": "single"},
            files={"file": ("preprocessing_sample.csv", handle, "text/csv")},
        )
    assert response.status_code == 201


def test_apply_pipeline_creates_exports_and_downloads(client):
    project = client.post("/projects", json={"name": "Export project"}).json()
    _upload(client, project["id"])
    analysis = client.post(
        f"/projects/{project['id']}/analysis/run",
        json={"target_column": "target", "problem_type": "classification", "mode": "single"},
    ).json()
    pipeline = client.post(
        f"/projects/{project['id']}/pipelines",
        json={"name": "export pipeline", "analysis_run_id": analysis["id"], "mode": "single"},
    ).json()
    client.post(
        f"/pipelines/{pipeline['id']}/steps",
        json={"operation_type": "numeric_imputation", "columns": ["income"], "params": {"strategy": "median"}},
    )
    client.post(
        f"/pipelines/{pipeline['id']}/steps",
        json={"operation_type": "drop_columns", "columns": ["city"], "params": {}},
    )

    response = client.post(f"/pipelines/{pipeline['id']}/apply", json={"limit": 20})

    assert response.status_code == 201
    run = response.json()
    assert run["status"] == "completed"
    assert set(run["output_paths"]) >= {"cleaned_single", "config", "report", "code"}
    for path in run["output_paths"].values():
        assert Path(path).exists()

    fetched = client.get(f"/pipeline-runs/{run['id']}")
    assert fetched.status_code == 200
    assert fetched.json()["id"] == run["id"]

    config = client.get(f"/pipeline-runs/{run['id']}/download/config")
    assert config.status_code == 200
    assert config.json()["pipeline_id"] == pipeline["id"]
    assert len(config.json()["steps"]) == 2

    report = client.get(f"/pipeline-runs/{run['id']}/download/report")
    assert report.status_code == 200
    assert "DataPrep Studio Preprocessing Report" in report.text

    code = client.get(f"/pipeline-runs/{run['id']}/download/code")
    assert code.status_code == 200
    assert "Generated by DataPrep Studio" in code.text

    cleaned = client.get(f"/pipeline-runs/{run['id']}/download/cleaned-single")
    assert cleaned.status_code == 200
    assert "city" not in cleaned.text.splitlines()[0]

    runs = client.get(f"/projects/{project['id']}/pipeline-runs")
    assert runs.status_code == 200
    assert [item["id"] for item in runs.json()] == [run["id"]]
