from io import StringIO
from pathlib import Path

import pandas as pd
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"


def _upload(client, project_id: int) -> None:
    with (FIXTURE_DIR / "preprocessing_sample.csv").open("rb") as handle:
        response = client.post(
            f"/projects/{project_id}/datasets/upload",
            data={"role": "single"},
            files={"file": ("preprocessing_sample.csv", handle, "text/csv")},
        )
    assert response.status_code == 201


def test_apply_pipeline_creates_exports_and_downloads(client):
    project = client.post("/projects", json={"name": "Export project"}).json()
    _upload(client, project["id"])
    analysis = client.post(
        f"/projects/{project['id']}/analysis/run",
        json={"target_column": "target", "problem_type": "classification", "mode": "single"},
    ).json()
    pipeline = client.post(
        f"/projects/{project['id']}/pipelines",
        json={"name": "export pipeline", "analysis_run_id": analysis["id"], "mode": "single"},
    ).json()
    client.post(
        f"/pipelines/{pipeline['id']}/steps",
        json={"operation_type": "numeric_imputation", "columns": ["income"], "params": {"strategy": "median"}},
    )
    client.post(
        f"/pipelines/{pipeline['id']}/steps",
        json={"operation_type": "drop_columns", "columns": ["city"], "params": {}},
    )

    response = client.post(f"/pipelines/{pipeline['id']}/apply", json={"limit": 20})

    assert response.status_code == 201
    run = response.json()
    assert run["status"] == "completed"
    assert set(run["output_paths"]) >= {"cleaned_single", "config", "report", "code"}
    for path in run["output_paths"].values():
        assert Path(path).exists()

    fetched = client.get(f"/pipeline-runs/{run['id']}")
    assert fetched.status_code == 200
    assert fetched.json()["id"] == run["id"]

    config = client.get(f"/pipeline-runs/{run['id']}/download/config")
    assert config.status_code == 200
    config_body = config.json()
    assert config_body["schema_version"] == "dataprep-studio.config.v1"
    assert config_body["pipeline_id"] == pipeline["id"]
    assert config_body["pipeline_name"] == "export pipeline"
    assert len(config_body["steps"]) == 2
    assert config_body["metadata"]["pipeline_name"] == "export pipeline"
    assert config_body["metadata"]["step_count"] == 2
    assert config_body["metadata"]["operation_types"] == ["numeric_imputation", "drop_columns"]
    assert config_body["metadata"]["before_summary"]["column_count"] == 4
    assert config_body["metadata"]["after_summary"]["column_count"] == 3

    report = client.get(f"/pipeline-runs/{run['id']}/download/report")
    assert report.status_code == 200
    assert "DataPrep Studio Preprocessing Report" in report.text
    assert "Pipeline name: export pipeline" in report.text

    code = client.get(f"/pipeline-runs/{run['id']}/download/code")
    assert code.status_code == 200
    assert "Generated by DataPrep Studio" in code.text

    cleaned = client.get(f"/pipeline-runs/{run['id']}/download/cleaned-single")
    assert cleaned.status_code == 200
    assert "city" not in cleaned.text.splitlines()[0]

    runs = client.get(f"/projects/{project['id']}/pipeline-runs")
    assert runs.status_code == 200
    assert [item["id"] for item in runs.json()] == [run["id"]]


def test_download_rejects_missing_export_artifact(client):
    project = client.post("/projects", json={"name": "Missing artifact project"}).json()
    _upload(client, project["id"])
    analysis = client.post(
        f"/projects/{project['id']}/analysis/run",
        json={"target_column": "target", "problem_type": "classification", "mode": "single"},
    ).json()
    pipeline = client.post(
        f"/projects/{project['id']}/pipelines",
        json={"name": "single export pipeline", "analysis_run_id": analysis["id"], "mode": "single"},
    ).json()
    client.post(
        f"/pipelines/{pipeline['id']}/steps",
        json={"operation_type": "numeric_imputation", "columns": ["income"], "params": {"strategy": "median"}},
    )
    run = client.post(f"/pipelines/{pipeline['id']}/apply", json={"limit": 20}).json()

    response = client.get(f"/pipeline-runs/{run['id']}/download/cleaned-train")

    assert response.status_code == 404
    assert response.json()["detail"] == "Requested export artifact is not available"


@pytest.mark.parametrize("mode", ["single", "train_test"])
def test_downloaded_code_reproduces_cleaned_csv(client, mode):
    project_id = client.post("/projects", json={"name": "Code replay"}).json()["id"]
    inputs = {"single": "age,city\n10,A\n,B\n30,A\n"} if mode == "single" else {
        "train": "age,city\n10,A\n,B\n30,A\n",
        "test": "age,city\n100,C\n,A\n",
    }
    for role, content in inputs.items():
        response = client.post(
            f"/projects/{project_id}/datasets/upload", data={"role": role},
            files={"file": (f"{role}.csv", content.encode(), "text/csv")},
        )
        assert response.status_code == 201
    pipeline_id = client.post(
        f"/projects/{project_id}/pipelines", json={"name": "Replay ' \\ pipeline", "mode": mode},
    ).json()["id"]
    for operation, columns, params in [
        ("add_missing_indicator", ["age"], {}),
        ("numeric_imputation", ["age"], {"strategy": "mean"}),
        ("one_hot_encoding", ["city"], {"drop_first": False}),
        ("numeric_scaling", ["age"], {"method": "standard"}),
    ]:
        response = client.post(f"/pipelines/{pipeline_id}/steps", json={
            "operation_type": operation, "columns": columns, "params": params,
        })
        assert response.status_code == 201
    response = client.post(f"/pipelines/{pipeline_id}/apply")
    assert response.status_code == 201, response.text
    run_id = response.json()["id"]
    code = client.get(f"/pipeline-runs/{run_id}/download/code").text
    namespace = {"__name__": "export_replay"}
    exec(code, namespace)
    assert namespace["CONFIG"] == client.get(f"/pipeline-runs/{run_id}/download/config").json()
    frames = {role: pd.read_csv(StringIO(content)) for role, content in inputs.items()}
    if mode == "single":
        replayed = {"single": namespace["preprocess_single"](frames["single"])}
    else:
        train, test = namespace["preprocess_train_test"](frames["train"], frames["test"])
        replayed = {"train": train, "test": test}
        assert namespace["CONFIG"]["steps"][1]["fitted"]["fill_values"]["age"] == 20
    for role, frame in replayed.items():
        exported = client.get(f"/pipeline-runs/{run_id}/download/cleaned-{role}")
        assert exported.status_code == 200
        pd.testing.assert_frame_equal(
            frame.reset_index(drop=True), pd.read_csv(StringIO(exported.text)), check_dtype=False,
        )
