import json


def generate_pipeline_code(config: dict[str, object]) -> str:
    config_json = json.dumps(config, indent=2, default=str)
    mode = config.get("mode", "single")
    return f'''"""
Generated by DataPrep Studio.

This code is a readable pandas-based reproduction helper for the exported preprocessing pipeline.
In train/test mode, learned preprocessing parameters are fit on train only and then applied to test.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd


CONFIG = {config_json}


def _safe_category(value: object) -> str:
    return "".join(char if char.isalnum() or char == "_" else "_" for char in str(value))


def apply_fitted_step(df: pd.DataFrame, step: dict) -> pd.DataFrame:
    working = df.copy()
    operation = step["operation_type"]
    columns = step.get("columns", [])
    fitted = step.get("fitted", {{}})

    if operation == "drop_columns":
        return working.drop(columns=[column for column in fitted.get("columns", columns) if column in working.columns])

    if operation == "remove_duplicate_rows":
        subset = [column for column in fitted.get("subset", columns) if column in working.columns]
        keep_value = fitted.get("keep", "first")
        keep = False if keep_value == "none" else keep_value
        return working.drop_duplicates(subset=subset or None, keep=keep)

    if operation == "replace_placeholder_values":
        for column in columns:
            if column in working.columns:
                working[column] = working[column].replace(fitted.get("placeholders", []), fitted.get("replacement"))
        return working

    if operation in {{"numeric_imputation", "categorical_imputation"}}:
        for column, value in fitted.get("fill_values", {{}}).items():
            if column in working.columns:
                working[column] = working[column].fillna(value)
        return working

    if operation == "add_missing_indicator":
        suffix = fitted.get("suffix", "_was_missing")
        for column in columns:
            if column in working.columns:
                working[f"{{column}}{{suffix}}"] = working[column].isna().astype(int)
        return working

    if operation == "rare_category_grouping":
        rare_label = fitted.get("rare_label", "__RARE__")
        for column, frequent_values in fitted.get("frequent_values", {{}}).items():
            if column in working.columns:
                mask = ~working[column].astype(str).isin(frequent_values) & working[column].notna()
                working.loc[mask, column] = rare_label
        return working

    if operation == "one_hot_encoding":
        for column, categories in fitted.get("categories", {{}}).items():
            if column not in working.columns:
                continue
            source = working[column].astype(str)
            for category in categories:
                working[f"{{column}}_{{_safe_category(category)}}"] = (source == category).astype(int)
            working = working.drop(columns=[column])
        return working

    if operation == "ordinal_encoding":
        unknown_value = fitted.get("unknown_value", -1)
        for column, mapping in fitted.get("mappings", {{}}).items():
            if column in working.columns:
                working[column] = working[column].astype(str).map(mapping).fillna(unknown_value).astype(int)
        return working

    if operation == "frequency_encoding":
        unknown_value = fitted.get("unknown_value", 0)
        for column, mapping in fitted.get("frequency_maps", {{}}).items():
            if column in working.columns:
                working[column] = working[column].astype(str).map(mapping).fillna(unknown_value)
        return working

    if operation == "numeric_scaling":
        method = fitted.get("method")
        for column, stats in fitted.get("stats", {{}}).items():
            if column not in working.columns:
                continue
            numeric = pd.to_numeric(working[column], errors="coerce")
            if method == "standard":
                working[column] = (numeric - stats["mean"]) / stats["std"]
            elif method == "minmax":
                denom = stats["max"] - stats["min"] or 1.0
                working[column] = ((numeric - stats["min"]) / denom) * (stats["high"] - stats["low"]) + stats["low"]
            elif method == "robust":
                denom = stats["q_high"] - stats["q_low"] or 1.0
                working[column] = (numeric - stats["q_low"]) / denom
        return working

    if operation == "outlier_clipping":
        for column, threshold in fitted.get("thresholds", {{}}).items():
            if column in working.columns:
                working[column] = pd.to_numeric(working[column], errors="coerce").clip(threshold["lower"], threshold["upper"])
        return working

    if operation == "log_transform":
        offset = float(fitted.get("offset", 0))
        replace_original = bool(fitted.get("replace_original", True))
        suffix = fitted.get("new_suffix", "_log")
        for column in columns:
            if column in working.columns:
                transformed = np.log1p(pd.to_numeric(working[column], errors="coerce") + offset)
                if replace_original:
                    working[column] = transformed
                else:
                    working[f"{{column}}{{suffix}}"] = transformed
        return working

    if operation == "datetime_extract":
        features = fitted.get("features", [])
        drop_original = bool(fitted.get("drop_original", True))
        date_format = fitted.get("date_format")
        for column in columns:
            if column not in working.columns:
                continue
            parsed = pd.to_datetime(working[column], format=date_format, errors="coerce")
            if "year" in features:
                working[f"{{column}}_year"] = parsed.dt.year
            if "month" in features:
                working[f"{{column}}_month"] = parsed.dt.month
            if "day" in features:
                working[f"{{column}}_day"] = parsed.dt.day
            if "day_of_week" in features:
                working[f"{{column}}_day_of_week"] = parsed.dt.dayofweek
            if "is_weekend" in features:
                working[f"{{column}}_is_weekend"] = parsed.dt.dayofweek.isin([5, 6]).astype(int)
            if drop_original:
                working = working.drop(columns=[column])
        return working

    if operation == "text_basic_features":
        lowercase = bool(fitted.get("lowercase", False))
        strip = bool(fitted.get("strip_whitespace", True))
        create_length = bool(fitted.get("create_length_feature", True))
        create_word_count = bool(fitted.get("create_word_count_feature", True))
        drop_original = bool(fitted.get("drop_original", False))
        for column in columns:
            if column not in working.columns:
                continue
            text = working[column].fillna("").astype(str)
            if strip:
                text = text.str.strip()
            if lowercase:
                text = text.str.lower()
            if create_length:
                working[f"{{column}}_length"] = text.str.len()
            if create_word_count:
                working[f"{{column}}_word_count"] = text.str.split().str.len()
            if drop_original:
                working = working.drop(columns=[column])
            else:
                working[column] = text
        return working

    if operation == "rename_columns":
        return working.rename(columns=fitted.get("rename_map", {{}}))

    if operation == "reorder_columns":
        order = [column for column in fitted.get("column_order", []) if column in working.columns]
        remaining = [column for column in working.columns if column not in order]
        return working[order + remaining]

    return working


def apply_pipeline(df: pd.DataFrame, config: dict = CONFIG) -> pd.DataFrame:
    working = df.copy()
    for step in config.get("steps", []):
        working = apply_fitted_step(working, step)
    return working


def preprocess_single(df: pd.DataFrame) -> pd.DataFrame:
    return apply_pipeline(df, CONFIG)


def preprocess_train_test(train_df: pd.DataFrame, test_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    # Leakage-safe rule: the fitted parameters embedded in CONFIG were learned from train only.
    return apply_pipeline(train_df, CONFIG), apply_pipeline(test_df, CONFIG)


if __name__ == "__main__":
    config_path = Path("preprocessing_config.json")
    if config_path.exists():
        loaded = json.loads(config_path.read_text(encoding="utf-8"))
        print(f"Loaded config for pipeline {{loaded.get('pipeline_id')}}")
    print("Mode: {mode}")
'''
